apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: tharuny123/cloudgateway
        ports:
        - containerPort: 9090
        env:
          # - name: EUREKA_SERVER_ADDRESS
          #   valueFrom:
          #     configMapKeyRef:
          #       key: eureka_service_address
          #       name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          # - name: OKTA_REDIRECT_URI
          #   valueFrom:
          #     configMapKeyRef:
          #       key: redirect-uri
          #       name: cloud-gateway-cm


---
# As it is the gateway which controls and manages all the traffic, we define loadbalancer for this using the type field
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer # keyline
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 9090

