
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: cloud-gateway-cm
# data:
#   redirect-uri: 'http://192.168.49.2:30947/login/oauth2/code/okta'

